[package]
name = "js_runtime"
version.workspace = true
edition.workspace = true

[dependencies]
ui_graphics = { path = "../ui_graphics" }
anyhow = "1.0"
serde_bytes = "=0.11.15"
blake3 = "1"
bytemuck = "1"
rodio = { version = "0.18.1", default-features = false, features = ["wav", "vorbis", "mp3"] }
deno_core = "0.249.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.3"
rusqlite = { version = "0.37", features = ["bundled"] }
specs = "0.20"
specs-derive = "0.4"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
