[workspace.package]
version = "0.1.1"
edition = "2021"
description = "Community crate for XR in Bevy"
repository = "https://github.com/awtterpip/bevy_oxr"
license = "MIT/Apache-2.0"

[workspace]
resolver = "2"
members = ["crates/*", "crates/bevy_openxr/examples/android"]

[workspace.dependencies]
bevy = { version = "0.14.0", default-features = false, features = [
	"bevy_render",
	"bevy_core_pipeline",
	"bevy_winit",
	"bevy_pbr",
	"bevy_asset",
	"bevy_gltf",
	"bevy_scene",
	"multi_threaded",
	"x11",
	"jpeg"
] }
bevy_egui = "0.28.0"
virtual-dom = { path = "crates/virtual_dom" }
js_runtime = { path = "crates/js_runtime" }


# ⚠️ Optimizaciones Mias ⚠️

# cargo build --release -p bevy_mod_openxr --example luna
# cargo run   --release -p bevy_mod_openxr --example luna

[profile.dev]
opt-level = 1               # mucho mejor que 0 y compila rápido
debug-assertions = true     # si querés mantener asserts; ponlo en false si buscas más fps
overflow-checks = false
incremental = true
codegen-units = 256

# Compila las dependencias (Bevy, glam, wgpu, egui, etc.) con -O3 incluso en dev:
[profile.dev.package."*"]
opt-level = 3

[profile.dev-optimized]
inherits = "dev"
opt-level = 2
debug-assertions = false
overflow-checks = false
codegen-units = 64

[profile.dev-optimized.package."*"]
opt-level = 3

# ⚠️ Optimizaciones Mias ⚠️
